version: "3.7"
services:
  mongodb:
    container_name: express
    ports:
      - '27017:27017'
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    depends_on:
      - mongodb
    ports:
      - '8080:8080'